-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 16:48:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste` DEFAULT CHARACTER SET utf8 ;
USE `teste` ;

-- -----------------------------------------------------
-- Table `teste`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`individuals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`individuals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `photo` VARCHAR(255) NULL,
  `birhtdate` DATE NOT NULL,
  `gender` ENUM('FEMALE', 'MALE', 'OTHER') NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_individuals_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_individuals_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `teste`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `country` VARCHAR(3) NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `complement` VARCHAR(45) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_addresses_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_addresses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `teste`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `area_code` VARCHAR(4) NOT NULL,
  `country_code` VARCHAR(4) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `mobile` TINYINT NULL DEFAULT 0,
  `residential` TINYINT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_phones_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_phones_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `teste`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
